version: '3'
services:
    nginx:
        restart: always
        build:
            context: ./nginx
            dockerfile: Dockerfile.dev
        ports:
            - 80:80
        depends_on:
            - campaign-server
    campaign-server:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - .:/app
        environment:
            - JAVA_OPTS= -DPOSTGRESS_SERVER=postgres.server.name
volumes:
    redis_data:
